import * as Icons from './Components/CmsIcons'
import TEXT from './Containers/Menu/Data/Text'

import SubIcon from '@material-ui/icons/RadioButtonCheckedOutlined'

export const PROJECT_ADMINISTRATOR = 'administrator'
export const PROJECT_MAIN = 'sisal'

export const PROVIDER_AD = 'ad'
export const DEFINE_ALL = 'all'
export const DEFAULT_ACTIONS = ['create', 'read', 'update', 'delete', 'all']
export const DEBOUCE_WAITING_TIME = 1500
export const DEFINE_SERVICES = [
    {service: 'cmsUser', endpoint: '', name: 'cms-user'},
    {service: 'remoteConfig', endpoint: '', name: 'remote-config'}
]

export const AdministratorDataMenu = [
    {
        text: TEXT.MENU_CMS_ADMINISTRATOR_OVERVIEW, link: `/administrator/overview`, icon: Icons.IconDashboard,
    },
    {
        text: TEXT.MENU_CMS_ADMINISTRATOR_GROUP, link: `/administrator/group`, icon: Icons.IconUsers,
    },
    {
        text: TEXT.MENU_CMS_ADMINISTRATOR_ROLE, link: `/administrator/role`, icon: Icons.IconAssign,
    },
]

export const MainDataMenu = [
    {
        text: TEXT.MENU_TYCOON_PROPERTY_MANAGEMENT, link: '/tycoon-property', icon: Icons.IconTycoonProperty,
        submenu: [
            {
                text: TEXT.MENU_TYCOON_PROPERTY_BUILDING_MANAGEMENT, link: '/tycoon-property/building', icon: SubIcon,
            },
            {
                text: TEXT.MENU_TYCOON_PROPERTY_CURRENCY_MANAGEMENT, link: '/tycoon-property/currency', icon: SubIcon,
            },
            {
                text: TEXT.MENU_TYCOON_PROPERTY_ACHIEVEMENT_MANAGEMENT, link: '/tycoon-property/achievement', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_TYCOON_PROPERTY_BADGE_MANAGEMENT, link: '/tycoon-property/badge', icon: SubIcon,
            // },
            // {
            //     text: TEXT.MENU_TYCOON_PROPERTY_CLUB_MANAGEMENT, link: '/tycoon-property/club', icon: SubIcon,
            // },
        ]
    },
    {
        text: TEXT.MENU_GAME_ECONOMY, link: '/game-economy', icon: Icons.IconGameEconomy,
        submenu: [
            {
                text: TEXT.MENU_GAME_ECONOMY_REWARD_MANAGEMENT, link: '/game-economy/reward', icon: SubIcon,
            },
            {
                text: TEXT.MENU_GAME_ECONOMY_SHOP_MANAGEMENT, link: '/game-economy/shop', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_GAME_ECONOMY_IAP, link: '/game-economy/iap', icon: SubIcon,
            // },
            // {
            //     text: TEXT.MENU_GAME_ECONOMY_ITEM_MANAGEMENT, link: '/game-economy/item', icon: SubIcon,
            // },
            // {
            //     text: TEXT.MENU_GAME_ECONOMY_PRIZE_MANAGEMENT, link: '/game-economy/prize', icon: SubIcon,
            // },
            {
                text: TEXT.MENU_GAME_ECONOMY_INSTANT_WIN, link: '/game-economy/instant-win', icon: SubIcon,
            },
        ]
    },
    {
        text: TEXT.MENU_CONTENT_MANAGEMENT, link: '/content', icon: Icons.IconContent,
        submenu: [
            {
                text: TEXT.MENU_CONTENT_PLAYER_CARD_MANAGEMENT, link: '/content/player-card', icon: SubIcon,
            },
            {
                text: TEXT.MENU_CONTENT_DOWNLOADABLE_CONTENT, link: '/content/downloadable', icon: SubIcon,
            },
            {
                text: TEXT.MENU_CONTENT_QUIZ_BANK_MANAGEMENT, link: '/content/quiz-bank', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_CONTENT_POP_IN_MANAGEMENT, link: '/content/pop-in', icon: SubIcon,
            // },
            {
                text: TEXT.MENU_CONTENT_QUEST_SYSTEM, link: '/content/quest-sytem', icon: SubIcon,
            },
        ]
    },
    {
        text: TEXT.MENU_REGISTERED_USER_MANAGEMENT, link: '/registered', icon: Icons.IconUsers,
        submenu: [
            {
                text: TEXT.MENU_REGISTERED_USER_USER_MANAGEMENT, link: '/registered/user', icon: SubIcon,
            },
            {
                text: TEXT.MENU_REGISTERED_USER_CONSENT_TRACKING, link: '/registered/consent-tracking', icon: SubIcon,
            },
            {
                text: TEXT.MENU_REGISTERED_USER_PROFILE_MANAGEMENT, link: '/registered/profile', icon: SubIcon,
            }
        ]
    },
    {
        text: TEXT.MENU_LIVE_OPERATIONS, link: '/live-operations', icon: Icons.IconLiveOperations,
        submenu: [
            {
                text: TEXT.MENU_LIVE_OPERATIONS_CAMPAIGN_MANAGEMENT, link: '/live-operations/campaign', icon: SubIcon,
            },
            {
                text: TEXT.MENU_LIVE_OPERATIONS_SPA_MANAGEMENT, link: '/live-operations/spa', icon: SubIcon,
            },
            {
                text: TEXT.MENU_LIVE_OPERATIONS_ONLINE_NOTIFICATION, link: '/live-operations/online-notification', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_LIVE_OPERATIONS_MARKET_PLACE_MANAGEMENT, link: '/live-operations/market-place', icon: SubIcon,
            // }
        ]
    },
    {
        text: TEXT.MENU_LEAGUE_MANAGEMENT, link: '/league', icon: Icons.IconLeaderboard,
        submenu: [
            {
                text: TEXT.MENU_LEAGUE_SEASON_MANAGEMENT, link: '/league/season', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_LEAGUE_TOURNAMENT_MANAGEMENT, link: '/league/tournament', icon: SubIcon,
            // },
            {
                text: TEXT.MENU_LEAGUE_LEADERBOARD, link: '/league/leaderboard', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_LEAGUE_CLAN_MANAGEMENT, link: '/league/clan', icon: SubIcon,
            // },
            // {
            //     text: TEXT.MENU_LEAGUE_MULTIPLAY_PVP_MANAGEMENT, link: '/league/multiplay-pvp', icon: SubIcon,
            // },
        ]
    },
    {
        text: TEXT.MENU_REMOTE_CONFIGURATION, link: '/remote-configuration', icon: Icons.IconRemoteConfig,
        submenu: [
            {
                text: TEXT.MENU_REMOTE_CONFIGURATION_OVERVIEW, link: '/remote-configuration/overview', icon: SubIcon,
            },
            {
                text: TEXT.MENU_REMOTE_CONFIGURATION_ENVIRONMENT, link: '/remote-configuration/environment', icon: SubIcon,
            }
        ]
    },
    {
        text: TEXT.MENU_TRACKING, link: '/tracking', icon: Icons.IconTracking,
        submenu: [
            {
                text: TEXT.MENU_TRACKING_ACTIVITY, link: '/tracking/activity', icon: SubIcon,
            },
            {
                text: TEXT.MENU_TRACKING_CMS_ACTVITY_LOG, link: '/tracking/cms-activity-log', icon: SubIcon,
            },
            // {
            //     text: TEXT.MENU_TRACKING_STORE_DATA, link: '/tracking/store-data', icon: SubIcon,
            // },
            {
                text: TEXT.MENU_TRACKING_ESB, link: '/tracking/esb', icon: SubIcon,
            },
        ]
    },
    {
        text: TEXT.MENU_OTHERS, link: '/others', icon: Icons.IconOthers,
        submenu: [
            {
                text: TEXT.MENU_OTHERS_CRON_MANAGEMENT, link: '/others/cron', icon: SubIcon,
            },
        ]
    }
]

export const DataProfileMenu = [
    {
        text: '', link: null, icon: null
    },
    {
        text: TEXT.MENU_PROFILE_SETTINGS, link: '/profile', icon: null
    },
    {
        text: TEXT.MENU_PROFILE_LOG_OUT, link: '/logout', icon: null
    }
]

export const ReportDateDelay = {
    'super_admin': 0,
    'admin': 0,
    'client_tech': 0,
    'client_marketing': 4,
    'gameloft_tech': 0,
    'gameloft_marketing': 4,
    'user': 4
}

export const SisalLogo = 'SisalLogo.png'
export const AdministratorLogo = 'Administrator.png'
export const Avatar = 'Avatar.png'

export const PageNotFoundLogo = 'WebPageNotFound.jpg'
export const PageUnderConstructionLogo = 'WebPageConstruction.jpg'
export const NoImgFound = 'noimage.png'

export const TimeZone = [
    { id: 'GMT +00:00', value: 0},
    { id: 'GMT +01:00', value: -1},
    { id: 'GMT +02:00', value: -2},
    { id: 'GMT +03:00', value: -3},
    { id: 'GMT +04:00', value: -4},
    { id: 'GMT +05:00', value: -5},
    { id: 'GMT +06:00', value: -6},
    { id: 'GMT +07:00', value: -7},
    { id: 'GMT +08:00', value: -8},
    { id: 'GMT +09:00', value: -9},
    { id: 'GMT +10:00', value: -10},
    { id: 'GMT +11:00', value: -11},
    { id: 'GMT +12:00', value: -12},
    { id: 'GMT -11:00', value: 11},
    { id: 'GMT -10:00', value: 10},
    { id: 'GMT -09:00', value: 9},
    { id: 'GMT -08:00', value: 8},
    { id: 'GMT -07:00', value: 7},
    { id: 'GMT -06:00', value: 6},
    { id: 'GMT -05:00', value: 5},
    { id: 'GMT -04:00', value: 4},
    { id: 'GMT -03:00', value: 3},
    { id: 'GMT -02:00', value: 2},
    { id: 'GMT -01:00', value: 1}
]

export const COUNTRY_LIST_SERVER = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'AndorrA', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },

    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bonaire', code: 'BQ' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },

    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cote D\'Ivoire', code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Curaçao', code: 'CW' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },

    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },

    { name: 'EAST TIMOR', code: 'TL' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'EUROPE (GENERIC)', code: 'EU' },

    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },

    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },

    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },

    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },

    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },

    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },

    { name: 'Lao People\'S Democratic Republic', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },

    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },

    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'NORTH KOREA', code: 'KP' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },

    { name: 'Oman', code: 'OM' },

    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },

    { name: 'Qatar', code: 'QA' },

    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'Rwanda', code: 'RW' },

    { name: 'SAINT BARTHELEMY', code: 'BL' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Martin (French part)', code: 'MF' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Sint Maarten (Dutch part)', code: 'SX' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'SOUTH KOREA', code: 'KR' },
    { name: 'South Sudan', code: 'SS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'ST VINCENT AND THE GRENADINES', code: 'VC' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },

    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },

    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'English', code: 'EN' },
    { name: 'United States', code: 'US' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uzbekistan', code: 'UZ' },

    { name: 'Vanuatu', code: 'VU' },
    { name: 'Vatican City State', code: 'VA' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },

    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },

    { name: 'Yemen', code: 'YE' },

    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' }
]

export const NATIONALITY_LIST_SERVER = [
    { code: 'GB', name: 'British' },
    { code: 'AF', name: 'Afghan' },
    { code: 'AL', name: 'Albanian' },
    { code: 'DZ', name: 'Algerian' },
    { code: 'US', name: 'American' },
    { code: 'AD', name: 'Andorran' },
    { code: 'AO', name: 'Angolan' },
    { code: 'AM', name: 'Armenian' },
    { code: 'AT', name: 'Austrian' },
    { code: 'AZ', name: 'Azerbaijani' },
    { code: 'AR', name: 'Argentinian' },
    { code: 'AU', name: 'Australian' },
    { code: 'BH', name: 'Bahraini' },
    { code: 'BD', name: 'Bangladeshi' },
    { code: 'BB', name: 'Barbadian' },
    { code: 'BY', name: 'Belarusian' },
    { code: 'BZ', name: 'Belizean' },
    { code: 'BJ', name: 'Beninese' },
    { code: 'BM', name: 'Bermudian' },
    { code: 'BT', name: 'Bhutanese' },
    { code: 'BO', name: 'Bolivian' },
    { code: 'BA', name: 'Bosnian' },
    { code: 'BW', name: 'Botswanan' },
    { code: 'BG', name: 'Bulgarian' },
    { code: 'BF', name: 'Burkinese' },
    { code: 'BI', name: 'Burundian' },
    { code: 'CA', name: 'Canadian' },
    { code: 'CN', name: 'Chinese' },
    { code: 'CO', name: 'Colombian' },
    { code: 'CU', name: 'Cuban' },
    { code: 'KH', name: 'Cambodian' },
    { code: 'CM', name: 'Cameroonian' },
    { code: 'CV', name: 'Cape Verdean' },
    { code: 'TD', name: 'Chadian' },
    { code: 'CL', name: 'Chilean' },
    { code: 'CG', name: 'Congolese' },
    { code: 'CR', name: 'Costa Rican' },
    { code: 'HR', name: 'Croat' },
    { code: 'CY', name: 'Cypriot' },
    { code: 'CZ', name: 'Czech' },
    { code: 'DK', name: 'Danish' },
    { code: 'DO', name: 'Dominican' },
    { code: 'DJ', name: 'Djiboutian' },
    { code: 'DM', name: 'Dominican' },
    { code: 'NL', name: 'Dutch' },
    { code: 'EC', name: 'Ecuadorean' },
    { code: 'EG', name: 'Egyptian' },
    { code: 'ER', name: 'Eritrean' },
    { code: 'EE', name: 'Estonian' },
    { code: 'ET', name: 'Ethiopian' },
    { code: 'FJ', name: 'Fijian' },
    { code: 'FI', name: 'Finnish' },
    { code: 'PF', name: 'French Polynesian' },
    { code: 'FR', name: 'French' },
    { code: 'GA', name: 'Gabonese' },
    { code: 'GM', name: 'Gambian' },
    { code: 'GE', name: 'Georgian' },
    { code: 'DE', name: 'German' },
    { code: 'GT', name: 'Guatemalan' },
    { code: 'GH', name: 'Ghanaian' },
    { code: 'GR', name: 'Greek' },
    { code: 'GD', name: 'Grenadian' },
    { code: 'GN', name: 'Guinean' },
    { code: 'GY', name: 'Guyanese' },
    { code: 'HT', name: 'Haitian' },
    { code: 'HN', name: 'Honduran' },
    { code: 'HU', name: 'Hungarian' },
    { code: 'IN', name: 'Indian' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IL', name: 'Israeli' },
    { code: 'IT', name: 'Italian' },
    { code: 'IS', name: 'Icelandic' },
    { code: 'ID', name: 'Indonesian' },
    { code: 'IR', name: 'Iranian' },
    { code: 'IQ', name: 'Iraqi' },
    { code: 'JP', name: 'Japanese' },
    { code: 'JM', name: 'Jamaican' },
    { code: 'JO', name: 'Jordanian' },
    { code: 'KZ', name: 'Kazakh' },
    { code: 'KE', name: 'Kenyan' },
    { code: 'KP', name: 'North Korean' },
    { code: 'KW', name: 'Kuwaiti' },
    { code: 'LV', name: 'Latvian' },
    { code: 'LB', name: 'Lebanese' },
    { code: 'LR', name: 'Liberian' },
    { code: 'LY', name: 'Libyan' },
    { code: 'LT', name: 'Lithuanian' },
    { code: 'LU', name: 'LUXEMBOURG' },
    { code: 'MG', name: 'Madagascan' },
    { code: 'MW', name: 'Malawian' },
    { code: 'MY', name: 'Malaysian' },
    { code: 'MV', name: 'Maldivian' },
    { code: 'ML', name: 'Malian' },
    { code: 'MT', name: 'Maltese' },
    { code: 'MR', name: 'Mauritanian' },
    { code: 'MU', name: 'Mauritian' },
    { code: 'MC', name: 'Monacan' },
    { code: 'MN', name: 'Mongolian' },
    { code: 'ME', name: 'Montenegrin' },
    { code: 'MA', name: 'Moroccan' },
    { code: 'MZ', name: 'Mozambican' },
    { code: 'MX', name: 'Mexican' },
    { code: 'NA', name: 'Namibian' },
    { code: 'NP', name: 'Nepalese' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'NI', name: 'Nicaraguan' },
    { code: 'NE', name: 'Nigerien' },
    { code: 'NG', name: 'Nigerian' },
    { code: 'NO', name: 'Norwegian' },
    { code: 'OM', name: 'Omani' },
    { code: 'PK', name: 'Pakistani' },
    { code: 'PA', name: 'Panamanian' },
    { code: 'PG', name: 'Guinean' },
    { code: 'PY', name: 'Paraguayan' },
    { code: 'PE', name: 'Peruvian' },
    { code: 'PH', name: 'Philippine' },
    { code: 'PL', name: 'Polish' },
    { code: 'PT', name: 'Portuguese' },
    { code: 'QA', name: 'Qatari' },
    { code: 'RO', name: 'Romanian' },
    { code: 'RW', name: 'Rwandan' },
    { code: 'SV', name: 'Salvadorean' },
    { code: 'AS', name: 'Samoan' },
    { code: 'SA', name: 'Saudi Arabian' },
    { code: 'SN', name: 'Senegalese' },
    { code: 'RS', name: 'Serbian' },
    { code: 'SL', name: 'Sierra Leonian' },
    { code: 'SG', name: 'Singaporean' },
    { code: 'SK', name: 'Slovak' },
    { code: 'SI', name: 'Slovenian' },
    { code: 'SB', name: 'Slomoni' },
    { code: 'SO', name: 'Somali' },
    { code: 'ZA', name: 'South African' },
    { code: 'KR', name: 'South Korean' },
    { code: 'ES', name: 'Spanish' },
    { code: 'SE', name: 'Swedish' },
    { code: 'CH', name: 'Swiss' },
    { code: 'LK', name: 'Sri Lankan' },
    { code: 'SD', name: 'Sudanese' },
    { code: 'SR', name: 'Surinamese' },
    { code: 'SZ', name: 'Swazi' },
    { code: 'TW', name: 'Taiwanese' },
    { code: 'TJ', name: 'Tajik' },
    { code: 'TH', name: 'Thai' },
    { code: 'TG', name: 'Togolese' },
    { code: 'TT', name: 'Trinidadian' },
    { code: 'TN', name: 'Tunisian' },
    { code: 'TR', name: 'Turkish' },
    { code: 'TM', name: 'Turkoman' },
    { code: 'TV', name: 'Tuvaluan' },
    { code: 'UG', name: 'Ugandan' },
    { code: 'UA', name: 'Ukrainian' },
    { code: 'AE', name: 'Emirati' },
    { code: 'VN', name: 'Vietnamese' },
    { code: 'UY', name: 'Uruguayan' },
    { code: 'UZ', name: 'Uzbek' },
    { code: 'VU', name: 'Vanuatuan' },
    { code: 'YE', name: 'Yemeni' },
    { code: 'ZM', name: 'Zambian' }
]

export const REGION_LIST_SERVER = [
    { name: 'US East (Ohio)', code: 'us-east-2' },
    { name: 'US East (N. Virginia)', code: 'us-east-1' },
    { name: 'US West (N. California)', code: 'us-west-1' },
    { name: 'US West (Oregon)', code: 'us-west-2' },
    { name: 'Africa (Cape Town)', code: 'af-south-1' },
    { name: 'Asia Pacific (Hong Kong)', code: 'ap-east-1' },
    { name: 'Asia Pacific (Mumbai)', code: 'ap-south-1' },
    { name: 'Asia Pacific (Osaka)', code: 'ap-northeast-3' },
    { name: 'Asia Pacific (Seoul)', code: 'ap-northeast-2' },
    { name: 'Asia Pacific (Singapore)', code: 'ap-southeast-1' },
    { name: 'Asia Pacific (Sydney)', code: 'ap-southeast-2' },
    { name: 'Asia Pacific (Tokyo)', code: 'ap-northeast-1' },
    { name: 'Canada (Central)', code: 'ca-central-1' },
    { name: 'Europe (Frankfurt)', code: 'eu-central-1' },
    { name: 'Europe (Ireland)', code: 'eu-west-1' },
    { name: 'Europe (London)', code: 'eu-west-2' },
    { name: 'Europe (Milan)', code: 'eu-south-1' },
    { name: 'Europe (Paris)', code: 'eu-west-3' },
    { name: 'Europe (Stockholm)', code: 'eu-north-1' },
    { name: 'Middle East (Bahrain)', code: 'me-south-1' },
    { name: 'South America (São Paulo)', code: 'sa-east-1' },
]

export const LANGUAGE_LIST_SERVER = [
    { code: 'ab', name: 'Abkhaz', nativeName: 'аҧсуа'},
    { code: 'aa', name: 'Afar', nativeName: 'Afaraf'},
    { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans'},
    { code: 'ak', name: 'Akan', nativeName: 'Akan'},
    { code: 'sq', name: 'Albanian', nativeName: 'Shqip'},
    { code: 'am', name: 'Amharic', nativeName: 'አማርኛ'},
    { code: 'ar', name: 'Arabic', nativeName: 'العربية'},
    { code: 'an', name: 'Aragonese', nativeName: 'Aragonés'},
    { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն'},
    { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'},
    { code: 'av', name: 'Avaric', nativeName: 'авар мацӀ, магӀарул мацӀ'},
    { code: 'ae', name: 'Avestan', nativeName: 'avesta'},
    { code: 'ay', name: 'Aymara', nativeName: 'aymar aru'},
    { code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili'},
    { code: 'bm', name: 'Bambara', nativeName: 'bamanankan'},
    { code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле'},
    { code: 'eu', name: 'Basque', nativeName: 'euskara, euskera'},
    { code: 'be', name: 'Belarusian', nativeName: 'Беларуская'},
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা'},
    { code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी'},
    { code: 'bi', name: 'Bislama', nativeName: 'Bislama'},
    { code: 'bs', name: 'Bosnian', nativeName: 'bosanski jezik'},
    { code: 'br', name: 'Breton', nativeName: 'brezhoneg'},
    { code: 'bg', name: 'Bulgarian', nativeName: 'български език'},
    { code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ'},
    { code: 'ca', name: 'Catalan; Valencian', nativeName: 'Català'},
    { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru'},
    { code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт'},
    { code: 'ny', name: 'Chichewa; Chewa; Nyanja', nativeName: 'chiCheŵa, chinyanja'},
    { code: 'zh', name: 'Chinese', nativeName: '中文 (Zhōngwén), 汉语, 漢語'},
    { code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи'},
    { code: 'kw', name: 'Cornish', nativeName: 'Kernewek'},
    { code: 'co', name: 'Corsican', nativeName: 'corsu, lingua corsa'},
    { code: 'cr', name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ'},
    { code: 'hr', name: 'Croatian', nativeName: 'hrvatski'},
    { code: 'cs', name: 'Czech', nativeName: 'česky, čeština'},
    { code: 'da', name: 'Danish', nativeName: 'dansk'},
    { code: 'dv', name: 'Divehi; Dhivehi; Maldivian;', nativeName: 'ދިވެހި'},
    { code: 'nl', name: 'Dutch', nativeName: 'Nederlands, Vlaams'},
    { code: 'en', name: 'English', nativeName: 'English'},
    { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto'},
    { code: 'et', name: 'Estonian', nativeName: 'eesti, eesti keel'},
    { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe'},
    { code: 'fo', name: 'Faroese', nativeName: 'føroyskt'},
    { code: 'fj', name: 'Fijian', nativeName: 'vosa Vakaviti'},
    { code: 'fi', name: 'Finnish', nativeName: 'suomi, suomen kieli'},
    { code: 'fr', name: 'French', nativeName: 'français, langue française'},
    { code: 'ff', name: 'Fula; Fulah; Pulaar; Pular', nativeName: 'Fulfulde, Pulaar, Pular'},
    { code: 'gl', name: 'Galician', nativeName: 'Galego'},
    { code: 'ka', name: 'Georgian', nativeName: 'ქართული'},
    { code: 'de', name: 'German', nativeName: 'Deutsch'},
    { code: 'el', name: 'Greek, Modern', nativeName: 'Ελληνικά'},
    { code: 'gn', name: 'Guaraní', nativeName: 'Avañeẽ'},
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'},
    { code: 'ht', name: 'Haitian; Haitian Creole', nativeName: 'Kreyòl ayisyen'},
    { code: 'ha', name: 'Hausa', nativeName: 'Hausa, هَوُسَ'},
    { code: 'he', name: 'Hebrew (modern)', nativeName: 'עברית'},
    { code: 'hz', name: 'Herero', nativeName: 'Otjiherero'},
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी, हिंदी'},
    { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu'},
    { code: 'hu', name: 'Hungarian', nativeName: 'Magyar'},
    { code: 'ia', name: 'Interlingua', nativeName: 'Interlingua'},
    { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia'},
    { code: 'ie', name: 'Interlingue', nativeName: 'Originally called Occidental; then Interlingue after WWII'},
    { code: 'ga', name: 'Irish', nativeName: 'Gaeilge'},
    { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo'},
    { code: 'ik', name: 'Inupiaq', nativeName: 'Iñupiaq, Iñupiatun'},
    { code: 'io', name: 'Ido', nativeName: 'Ido'},
    { code: 'is', name: 'Icelandic', nativeName: 'Íslenska'},
    { code: 'it', name: 'Italian', nativeName: 'Italiano'},
    { code: 'iu', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ'},
    { code: 'ja', name: 'Japanese', nativeName: '日本語 (にほんご／にっぽんご)'},
    { code: 'jv', name: 'Javanese', nativeName: 'basa Jawa'},
    { code: 'kl', name: 'Kalaallisut, Greenlandic', nativeName: 'kalaallisut, kalaallit oqaasii'},
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'},
    { code: 'kr', name: 'Kanuri', nativeName: 'Kanuri'},
    { code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी, كشميري‎'},
    { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі'},
    { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ'},
    { code: 'ki', name: 'Kikuyu, Gikuyu', nativeName: 'Gĩkũyũ'},
    { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda'},
    { code: 'ky', name: 'Kirghiz, Kyrgyz', nativeName: 'кыргыз тили'},
    { code: 'kv', name: 'Komi', nativeName: 'коми кыв'},
    { code: 'kg', name: 'Kongo', nativeName: 'KiKongo'},
    { code: 'ko', name: 'Korean', nativeName: '한국어 (韓國語), 조선말 (朝鮮語)'},
    { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî, كوردی‎'},
    { code: 'kj', name: 'Kwanyama, Kuanyama', nativeName: 'Kuanyama'},
    { code: 'la', name: 'Latin', nativeName: 'latine, lingua latina'},
    { code: 'lb', name: 'Luxembourgish, Letzeburgesch', nativeName: 'Lëtzebuergesch'},
    { code: 'lg', name: 'Luganda', nativeName: 'Luganda'},
    { code: 'li', name: 'Limburgish, Limburgan, Limburger', nativeName: 'Limburgs'},
    { code: 'ln', name: 'Lingala', nativeName: 'Lingála'},
    { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ'},
    { code: 'lt', name: 'Lithuanian', nativeName: 'lietuvių kalba'},
    { code: 'lu', name: 'Luba-Katanga', nativeName: ''},
    { code: 'lv', name: 'Latvian', nativeName: 'latviešu valoda'},
    { code: 'gv', name: 'Manx', nativeName: 'Gaelg, Gailck'},
    { code: 'mk', name: 'Macedonian', nativeName: 'македонски јазик'},
    { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy fiteny'},
    { code: 'ms', name: 'Malay', nativeName: 'bahasa Melayu, بهاس ملايو‎'},
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'},
    { code: 'mt', name: 'Maltese', nativeName: 'Malti'},
    { code: 'mi', name: 'Māori', nativeName: 'te reo Māori'},
    { code: 'mr', name: 'Marathi (Marāṭhī)', nativeName: 'मराठी'},
    { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ'},
    { code: 'mn', name: 'Mongolian', nativeName: 'монгол'},
    { code: 'na', name: 'Nauru', nativeName: 'Ekakairũ Naoero'},
    { code: 'nv', name: 'Navajo, Navaho', nativeName: 'Diné bizaad, Dinékʼehǰí'},
    { code: 'nb', name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål'},
    { code: 'nd', name: 'North Ndebele', nativeName: 'isiNdebele'},
    { code: 'ne', name: 'Nepali', nativeName: 'नेपाली'},
    { code: 'ng', name: 'Ndonga', nativeName: 'Owambo'},
    { code: 'nn', name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk'},
    { code: 'no', name: 'Norwegian', nativeName: 'Norsk'},
    { code: 'ii', name: 'Nuosu', nativeName: 'ꆈꌠ꒿ Nuosuhxop'},
    { code: 'nr', name: 'South Ndebele', nativeName: 'isiNdebele'},
    { code: 'oc', name: 'Occitan', nativeName: 'Occitan'},
    { code: 'oj', name: 'Ojibwe, Ojibwa', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ'},
    { code: 'cu', name: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', nativeName: 'ѩзыкъ словѣньскъ'},
    { code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo'},
    { code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ'},
    { code: 'os', name: 'Ossetian, Ossetic', nativeName: 'ирон æвзаг'},
    { code: 'pa', name: 'Panjabi, Punjabi', nativeName: 'ਪੰਜਾਬੀ, پنجابی‎'},
    { code: 'pi', name: 'Pāli', nativeName: 'पाऴि'},
    { code: 'fa', name: 'Persian', nativeName: 'فارسی'},
    { code: 'pl', name: 'Polish', nativeName: 'polski'},
    { code: 'ps', name: 'Pashto, Pushto', nativeName: 'پښتو'},
    { code: 'pt', name: 'Portuguese', nativeName: 'Português'},
    { code: 'qu', name: 'Quechua', nativeName: 'Runa Simi, Kichwa'},
    { code: 'rm', name: 'Romansh', nativeName: 'rumantsch grischun'},
    { code: 'rn', name: 'Kirundi', nativeName: 'kiRundi'},
    { code: 'ro', name: 'Romanian, Moldavian, Moldovan', nativeName: 'română'},
    { code: 'ru', name: 'Russian', nativeName: 'русский язык'},
    { code: 'sa', name: 'Sanskrit (Saṁskṛta)', nativeName: 'संस्कृतम्'},
    { code: 'sc', name: 'Sardinian', nativeName: 'sardu'},
    { code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी, سنڌي، سندھی‎'},
    { code: 'se', name: 'Northern Sami', nativeName: 'Davvisámegiella'},
    { code: 'sm', name: 'Samoan', nativeName: 'gagana faa Samoa'},
    { code: 'sg', name: 'Sango', nativeName: 'yângâ tî sängö'},
    { code: 'sr', name: 'Serbian', nativeName: 'српски језик'},
    { code: 'gd', name: 'Scottish Gaelic; Gaelic', nativeName: 'Gàidhlig'},
    { code: 'sn', name: 'Shona', nativeName: 'chiShona'},
    { code: 'si', name: 'Sinhala, Sinhalese', nativeName: 'සිංහල'},
    { code: 'sk', name: 'Slovak', nativeName: 'slovenčina'},
    { code: 'sl', name: 'Slovene', nativeName: 'slovenščina'},
    { code: 'so', name: 'Somali', nativeName: 'Soomaaliga, af Soomaali'},
    { code: 'st', name: 'Southern Sotho', nativeName: 'Sesotho'},
    { code: 'es', name: 'Spanish; Castilian', nativeName: 'español, castellano'},
    { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda'},
    { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili'},
    { code: 'ss', name: 'Swati', nativeName: 'SiSwati'},
    { code: 'sv', name: 'Swedish', nativeName: 'svenska'},
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'},
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు'},
    { code: 'tg', name: 'Tajik', nativeName: 'тоҷикӣ, toğikī, تاجیکی‎'},
    { code: 'th', name: 'Thai', nativeName: 'ไทย'},
    { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ'},
    { code: 'bo', name: 'Tibetan Standard, Tibetan, Central', nativeName: 'བོད་ཡིག'},
    { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen, Түркмен'},
    { code: 'tl', name: 'Tagalog', nativeName: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔'},
    { code: 'tn', name: 'Tswana', nativeName: 'Setswana'},
    { code: 'to', name: 'Tonga (Tonga Islands)', nativeName: 'faka Tonga'},
    { code: 'tr', name: 'Turkish', nativeName: 'Türkçe'},
    { code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga'},
    { code: 'tt', name: 'Tatar', nativeName: 'татарча, tatarça, تاتارچا‎'},
    { code: 'tw', name: 'Twi', nativeName: 'Twi'},
    { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti'},
    { code: 'ug', name: 'Uighur, Uyghur', nativeName: 'Uyƣurqə, ئۇيغۇرچە‎'},
    { code: 'uk', name: 'Ukrainian', nativeName: 'українська'},
    { code: 'ur', name: 'Urdu', nativeName: 'اردو'},
    { code: 'uz', name: 'Uzbek', nativeName: 'zbek, Ўзбек, أۇزبېك‎'},
    { code: 've', name: 'Venda', nativeName: 'Tshivenḓa'},
    { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt'},
    { code: 'vo', name: 'Volapük', nativeName: 'Volapük'},
    { code: 'wa', name: 'Walloon', nativeName: 'Walon'},
    { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg'},
    { code: 'wo', name: 'Wolof', nativeName: 'Wollof'},
    { code: 'fy', name: 'Western Frisian', nativeName: 'Frysk'},
    { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa'},
    { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש'},
    { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá'},
    { code: 'za', name: 'Zhuang, Chuang', nativeName: 'Saɯ cueŋƅ, Saw cuengh'}
]
